<?php
include_once("db_conx.php");




$cn = 1;
$cp = 2;
$cb = 257;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 2;
$cp = 3;
$cb = 269;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 3;
$cp = 4;
$cb = 297;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 4;
$cp = 5;
$cb = 212;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 5;
$cp = 6;
$cb = 201;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 6;
$cp = 7;
$cb = 206;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 7;
$cp = 8;
$cb = 205;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 8;
$cp = 9;
$cb = 297;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 9;
$cp = 10;
$cb = 205;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 10;
$cp = 11;
$cb = 214;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 11;
$cp = 12;
$cb = 215;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 12;
$cp = 13;
$cb = 281;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 13;
$cp = 14;
$cb = 280;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 14;
$cp = 15;
$cb = 202;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 15;
$cp = 16;
$cb = 268;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 16;
$cp = 17;
$cb = 281;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 17;
$cp = 18;
$cb = 240;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 18;
$cp = 19;
$cb = 225;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 19;
$cp = 20;
$cb = 252;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 20;
$cp = 21;
$cb = 258;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 21;
$cp = 22;
$cb = 205;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 22;
$cp = 23;
$cb = 218;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 23;
$cp = 24;
$cb = 200;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 24;
$cp = 25;
$cb = 230;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 25;
$cp = 26;
$cb = 217;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 26;
$cp = 27;
$cb = 242;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 27;
$cp = 28;
$cb = 219;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 28;
$cp = 29;
$cb = 239;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 29;
$cp = 30;
$cb = 275;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 30;
$cp = 31;
$cb = 261;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 31;
$cp = 32;
$cb = 275;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 32;
$cp = 33;
$cb = 266;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 33;
$cp = 34;
$cb = 203;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 34;
$cp = 35;
$cb = 234;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 35;
$cp = 36;
$cb = 264;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 36;
$cp = 37;
$cb = 239;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 37;
$cp = 38;
$cb = 287;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 38;
$cp = 39;
$cb = 279;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 39;
$cp = 40;
$cb = 249;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 40;
$cp = 41;
$cb = 276;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 41;
$cp = 42;
$cb = 290;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 42;
$cp = 43;
$cb = 248;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 43;
$cp = 44;
$cb = 208;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 44;
$cp = 45;
$cb = 282;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 45;
$cp = 46;
$cb = 267;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 46;
$cp = 47;
$cb = 216;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 47;
$cp = 48;
$cb = 209;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 48;
$cp = 49;
$cb = 244;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 49;
$cp = 50;
$cb = 285;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 50;
$cp = 51;
$cb = 296;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 51;
$cp = 52;
$cb = 209;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 52;
$cp = 53;
$cb = 216;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 53;
$cp = 54;
$cb = 233;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 54;
$cp = 55;
$cb = 237;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 55;
$cp = 56;
$cb = 253;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 56;
$cp = 57;
$cb = 242;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 57;
$cp = 58;
$cb = 293;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 58;
$cp = 59;
$cb = 200;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 59;
$cp = 60;
$cb = 292;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 60;
$cp = 61;
$cb = 201;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 61;
$cp = 62;
$cb = 297;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 62;
$cp = 63;
$cb = 253;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 63;
$cp = 64;
$cb = 300;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 64;
$cp = 65;
$cb = 244;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 65;
$cp = 66;
$cb = 212;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 66;
$cp = 67;
$cb = 246;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 67;
$cp = 68;
$cb = 249;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 68;
$cp = 69;
$cb = 208;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 69;
$cp = 70;
$cb = 271;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 70;
$cp = 71;
$cb = 224;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 71;
$cp = 72;
$cb = 218;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 72;
$cp = 73;
$cb = 210;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 73;
$cp = 74;
$cb = 217;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 74;
$cp = 75;
$cb = 222;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 75;
$cp = 76;
$cb = 243;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 76;
$cp = 77;
$cb = 222;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 77;
$cp = 78;
$cb = 242;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 78;
$cp = 79;
$cb = 208;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 79;
$cp = 80;
$cb = 217;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 80;
$cp = 81;
$cb = 261;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 81;
$cp = 82;
$cb = 299;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 82;
$cp = 83;
$cb = 240;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 83;
$cp = 84;
$cb = 213;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 84;
$cp = 85;
$cb = 255;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 85;
$cp = 86;
$cb = 214;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 86;
$cp = 87;
$cb = 292;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 87;
$cp = 88;
$cb = 238;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 88;
$cp = 89;
$cb = 237;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 89;
$cp = 90;
$cb = 280;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);



$cn = 90;
$cp = 91;
$cb = 273;
$sql = "INSERT INTO validity (creditno,creditpass,creditbalance) VALUES ('$cn','$cp','$cb')";
mysqli_query($db_conx,$sql);

?>


